name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  doclint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install codespell
      - name: Codespell (README & docs)
        run: |
          codespell \
            README.md \
            data/README.md \
            docs/*.md \
            docs/**/*.md \
            --ignore-words-list=RUL,RMSE,MAE,R^2,EIS,HPPC,UDDS,CC-BY

  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --no-banner
