name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  doclint:
    name: Codespell (docs lint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install codespell
        run: pip install codespell
      - name: Run codespell
        run: |
          codespell \
            -I .codespell-ignore-words.txt \
            --skip=".git,*.png,*.jpg,*.svg,*.pdf,*.ipynb_checkpoints,data/raw,results" \
            --quiet-level=2 \
            .

  secrets:
    name: Gitleaks (secrets scan)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git -v --config .gitleaks.toml
