name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  doclint:
    name: Codespell (docs lint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install codespell
        run: pip install codespell
      - name: Run codespell
        run: |
          codespell \
            README.md \
            data/README.md \
            docs/*.md \
            docs/**/*.md \
            --ignore-words-list="RUL,RMSE,MAE,R^2,EIS,HPPC,UDDS,CC-BY,GitHub,ipynb"

  safety:
    name: Gitleaks (secrets scan)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # scan full history as recommended
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional toggles:
          # GITLEAKS_ENABLE_UPLOAD_ARTIFACT: "true"
          # GITLEAKS_ENABLE_SUMMARY: "true"
          GITLEAKS_CONFIG: .gitleaks.toml
